---
- hosts: all
  become: yes
  gather_facts: no
  roles:
    - firewall

- hosts: server
  gather_facts: no
  become: yes
  roles:
    - server

- hosts: client
  gather_facts: no
  become: yes
  roles:
    - client