---
- name: Playbook to configure IPA server
  hosts: ipaserver
  become: true

  roles:
  - role: ipaserver
    state: present

- name: Playbook to configure IPA client
  hosts: cl01
  become: true

  roles:
  - role: ipaclient
    state: present