---
- name: install mail client app
  yum:
    name: mailx
    state: present
  
- name: install postfix
  yum:
    name: postfix
    state: present
  notify: restart postfix

- name: copy client config file
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
  notify: restart postfix