---
- hosts: all
  name: INSTALL MYSQL 
  become: yes

  tasks:

  - name: Download MySQL Community Repo
    get_url:
      url: http://repo.mysql.com/mysql80-community-release-el7.rpm
      dest: /tmp

  - name: Install MySQL Community Repo
    yum: name=/tmp/mysql80-community-release-el7.rpm state=present

  - name: Install MySQL Server
    yum: name=mysql-server state=present

  - name: Install MySQL-python, this is required for the task remove anonymous user
    yum: name=MySQL-python state=present

  - name: Start MySQL Server and enable it
    service: name=mysqld state=started enabled=yes