---
- name: install nfs
  yum:
    name: nfs-utils
    state: present

- name: create mount dir
  file:
    path: /var/nfs
    state: directory
    mode: '0777'
    
- name: mount nfs share
  mount:
    path: /var/nfs
    src: 192.168.56.150:/var/nfs
    fstype: nfs
    opts: auto,x-systemd.automount,x-systemd.device-timeout=10,timeo=14,vers=3,proto=udp
    state: mounted  
