---
# tasks file for percona-cluster
- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
    policy: targeted
    state: permissive

- name: Install repository
  yum:
    name: https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    state: present

- name: Install Percona XtraDB Cluster
  yum:
    name: Percona-XtraDB-Cluster-57
    state: present

- name: Started mysql daemon
  service: 
    name: mysql
    state: started
    enabled: yes
  tags: installation

- name: update mysql root password for all root accounts
  mysql_user:
    name: "{{ mysql_name_user }}"
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    login_user: "{{ mysql_name_user }}"
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - ::1
    - 127.0.0.1
    - localhost
    - eth1
  tags: installation

- name: Remove the test database
  mysql_db:
    login_user: "{{ mysql_name_user }}"
    login_password: "{{ mysql_root_password }}"
    name: test
    state: absent
  tags: installation

- name: Remove anonymous users
  mysql_user:
    login_user: "{{ mysql_name_user }}"
    login_password: "{{ mysql_root_password }}"
    user: "{{ mysql_name_user }}"
    name: ''
    host: "{{ item }}"
    state: absent
  with_items:
    - ::1
    - 127.0.0.1
    - localhost
    - eth1
  tags: installation

- name: Create new user sstuser
  mysql_user:
    name: "{{ mysql_user_sst }}"
    host: "{{ item }}"
    password: "{{ mysql_password_sst }}"
    login_user: "{{ mysql_name_user }}"
    login_password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
    state: present
  with_items:
    - ::1
    - 127.0.0.1
    - localhost
    - eth1
  tags: installation

- name: Start bootstrap.service
  service:
    name: mysql@bootstrap.service