---
- name: updgrade all packages
  yum:
    name: '*'
    state: latest

- name: install epel
  yum:
    name: epel-release

- name: Install packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - ipa-server
    - ipa-server-dns

- name: Change /etc/hosts
  copy:
    src: hosts
    dest: /etc/hosts

- name: IPA-Server install
  ignore_errors: True
  register: result
  command: ipa-server-install --hostname={{ server }} --domain={{ domain }} --realm={{ realm }} --ds-password={{ dmpassword }} --admin-password={{ password }} --mkhomedir --setup-dns --forwarder=8.8.8.8 --auto-reverse --unattended
  notify:
    - restart ipa