---
    - name: 'This is our playbook'
      hosts: proxy
      gather_facts: true
      become: true
      vars:
        proxy_addr: 192.168.11.244
        yum_packages:
            - bind-utils
            - tree
            - telnet
            - vim
        employes:
            - name: 'Parshin Dmitriy'
              position: DBA Teamleads

      tasks:

        - debug:
            var: proxy_addr

        - debug:
            msg: 'Install packages {{ item }}'
          loop: "{{ yum_packages }}"

        - yum:
            name: "{{ item }}"
            state: present
          loop: "{{ yum_packages }}"

        - shell: 'cat /etc.hostname'
          register: my_hostname

        - debug:
            var: my_hostname.stdout

        - set_fackt:
            new_hostname: "{{ my_hostaname.stdout }}-otus"

        - shell: 'echo {{ new_hostname }} > /home/vagrant/hostname'

        - name: 'Install yum_pakages'
          yum:
            name: telnet
            state: present
          when: ansible_os_famely=='RedHat'

        - name: 'Install apt'
          apt:
            name: telnet
            
    