---
# tasks file for deploy-rsyslog
- name: RSYSLOG | install rsyslog
  yum:
    name: rsyslog
    state: present
  notify:
    - restart rsyslog
  tags:
    - rsyslog-package
    - packages

- name: RSYSLOG | Configure rsyslog to send critical errors to log server
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
  notify:
    - restart rsyslog
  tags:
    - rsyslog-configuration

