---
- name: Disable network interface eth0
  serial: 1
  hosts: eth0
  become: true

  tasks:
    - name:
      nmcli:
        conn_name: '{{ item.conn_name }}'
        autoconnect: no
        state: absent
      with_items:
        - conn_name: "System eth0"
        - conn_name: "Wired connection 1"