---
all:
  children:
    proxy:

proxy:
  hosts:
    staging-nginx-01:
      ansible_host: 127.0.0.1
      ansible_port: 2201
      ansible_ssh_private_key_file: /home/dparshin/otus/linux_admin/Lesson_10/.vagrant/machines/staging-nginx-01/virtualbox/private_key