---
- name: Add records to /etc/hosts
  hosts: all
  become: True
  gather_facts: False
  roles:
    - role: hosts
      ip: 192.168.11.20
      dns: mail.home.local
    - role: hosts
      ip: 192.168.11.25
      dns: cl01.home.local

- name: Setup mail server
  become: True
  hosts: mail
  gather_facts: False
  roles:
    - role: postfix-server
      allowed_networks: "192.168.11.0/24"
      listen_ip: "192.168.11.20, 10.0.2.15"
    - role: dovecot
      user: vagrant
      password: password

- name: Setup postfix client
  become: True
  hosts: cl01
  gather_facts: False
  roles:
    - role: postfix-client
      relay_host: mail.otus.local