---
# tasks file for auditd-client
- name: AUDITD | install
  yum:
    name: audit-libs
    state: present
  notify:
    - restart auditd

- name: install audisp plugin for remote logging
  yum:
    name: audispd-plugins
    state: present

- name: config remote server ip
  lineinfile:
    path: /etc/audisp/audisp-remote.conf
    regexp: 'remote_server ='
    line: 'remote_server = {{ log_server }}'
    backrefs: yes
  notify: restart auditd

- name: enable auditd remote logging
  lineinfile:
    path: /etc/audisp/plugins.d/au-remote.conf
    regexp: 'active = no'
    line: 'active = yes'
    backrefs: yes
  notify: restart auditd

- name: disable local auditd logging
  lineinfile:
    path: /etc/audit/auditd.conf
    line: 'write_logs = no'
    state: present
  notify: restart auditd

- name: add audit rule to monitor config changes
  template:
      dest: /etc/audit/rules.d/{{ audit_key }}.rules
      src: templates/audit.rules.j2
  notify: restart auditd