---
- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
    policy: targeted
    state: permissive

- name: Enable and start firewalld
  systemd:
    name: firewalld
    enabled: yes
    state: started

- name: Add eth1 to public zone
  firewalld:
    zone: public
    interface: eth1
    state: enabled
    permanent: yes
    immediate: yes

- name: add services to firewall to public zone
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    zone: public
  with_items:
    - nfs
    - rpc-bind
    - mountd

- name: Enable port
  firewalld:
    port: 4001/udp
    permanent: yes
    state: enabled

- name: Enable port
  firewalld:
    port: 4001/tcp
    permanent: yes
    state: enabled

- name: Enable port
  firewalld:
    port: 2049/tcp
    permanent: yes
    state: enabled

- name: Enable port
  firewalld:
    port: 2049/udp
    permanent: yes
    state: enabled
    
- name: restart firewall
  service: 
    name: firewalld
    state: restarted
